package chart

import (
	"os"
	"time"

	"github.com/drizzleL/dumb_trader/model"
	"github.com/go-echarts/go-echarts/v2/charts"
	"github.com/go-echarts/go-echarts/v2/opts"
	"github.com/shopspring/decimal"
)

func getLineData(lines []decimal.Decimal) (ret []opts.LineData) {
	for _, line := range lines {
		ret = append(ret, opts.LineData{
			Value: line})
	}
	return
}

func PrintMacd(klines *model.Klines, f *os.File) {
	bar := charts.NewLine()
	bar.SetGlobalOptions(
		charts.WithTitleOpts(opts.Title{
			Title:    "My first bar chart generated by go-echarts",
			Subtitle: "It's extremely easy to use, right?",
		}),
		charts.WithYAxisOpts(opts.YAxis{
			Scale: true,
		}),
		charts.WithInitializationOpts(opts.Initialization{
			Width:  "1200px", // 设置画布宽度
			Height: "600px",  // 设置画布高度
		}),
		charts.WithTooltipOpts(opts.Tooltip{
			Show:    true,
			Trigger: "axis",
		}),
	)

	// Put data into instance
	xaxis := []string{}
	for _, line := range klines.Original {
		xaxis = append(xaxis, time.UnixMilli(line.CloseTime).Format("2006-01-02 15:04:05"))
	}
	bar.SetXAxis(xaxis)
	bar.AddSeries("macd", getLineData(klines.Data["macd"]))
	bar.Render(f)
}

func PrintEma(klines *model.Klines, f *os.File) {
	bar := charts.NewLine()
	bar.SetGlobalOptions(
		charts.WithTitleOpts(opts.Title{
			Title:    "My first bar chart generated by go-echarts",
			Subtitle: "It's extremely easy to use, right?",
		}),
		charts.WithYAxisOpts(opts.YAxis{
			Scale: true,
		}),
		charts.WithInitializationOpts(opts.Initialization{
			Width:  "1200px", // 设置画布宽度
			Height: "600px",  // 设置画布高度
		}),
		charts.WithTooltipOpts(opts.Tooltip{
			Show:    true,
			Trigger: "axis",
		}),
	)

	// Put data into instance
	xaxis := []string{}
	for _, line := range klines.Original {
		xaxis = append(xaxis, time.UnixMilli(line.CloseTime).Format("2006-01-02 15:04:05"))
	}
	bar.SetXAxis(xaxis)
	bar.AddSeries("base", getLineData(klines.CloseData))
	bar.AddSeries("ma20", getLineData(klines.Data["ma20"]))
	bar.AddSeries("ma60", getLineData(klines.Data["ma60"]))
	bar.AddSeries("ma120", getLineData(klines.Data["ma120"]))

	bar.AddSeries("ema20", getLineData(klines.Data["ema20"]))
	bar.AddSeries("ema60", getLineData(klines.Data["ema60"]))
	bar.AddSeries("ema120", getLineData(klines.Data["ema120"]))
	bar.Render(f)
}
